### ISSUE TITLE
API key question

### ISSUE THREAD

**Issue by citnadxela** [gabrielsroka/OktaAPI.psm1#3]
Got everything working like i mentioned.  However, my goal is to include this in an already existing PowerShell script that I have.  Currently, I have this included in the script:

Import-Module OktaAPI
Connect-Okta "MY_API_KEY" "https://my-org.okta.com"
    
$user = *User running the script enters user info here.

Disable-OktaUser $user

Everything is working.  My question is, my API key is open to anyone that opens the script.  Is there a way you would recommend in that anyone can run the script, but the API key is concealed?  Again, appreciate the help.

**Comment by gabrielsroka** [comment]
You could ask on devforum.okta.com, since this is an Okta question.

You can encrypt it. You could make it a non super admin to restrict the permissions. Who would you be giving the script to?

**Comment by citnadxela** [comment]
The script will exist on a server where colleagues will run it from.  But, I'll look into Okta's devforums.  Thanks again.

**Comment by adantic** [comment]
When I tried running it on a different server for more testing, I get the following:

PS C:\Windows\system32> Connect-Okta "$key" "https://myorg.okta.com"
Unable to find type [Runtime.InteropServices.RuntimeInformation].
At C:\Program Files\WindowsPowerShell\Modules\OktaAPI\1.0.12\OktaAPI.psm1:17 char:15
     $osDesc = [Runtime.InteropServices.RuntimeInformation]::OSDescrip ...
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     CategoryInfo          : InvalidOperation: (Runtime.Interop...timeInformation:TypeName) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound

I figured because this new server that I'm trying to run it on is a Windows Server 2016 box.  In the module, there's no 'if' option for that.  When I run:

[Runtime.InteropServices.RuntimeInformation]::OSDescription

to find the OS description, it's unable to find it's type.  Any ideas/recommendations on how I can make it work wi/ Server 2016?

**Comment by gabrielsroka** [comment]
I don't have access to Windows Server 2016. Can you try:
`[system.Runtime.InteropServices.RuntimeInformation]::OSDescription`

also, please reach out to me at
```
$company = "okta"
$firstName = "gabriel"
$lastName = "sroka"
$email = "$firstName.$lastName@$company.com"
```

**Comment by gabrielsroka** [comment]
@adantic, did installing the .NET Framework solve the issue?

**Comment by gabrielsroka** [comment]
@adantic I'm glad installing .NET helped. I'll see if I can remove the dependency.

**Comment by daviscraigs** [comment]
Hi Gabriel,
I'm new to using APIs and am working on a PowerShell script to automate the download of Okta system logs.  I have Get-OktaLogs working and am able to capture the numbers of log entries based on the -limit value.  My understanding is I should be able to then pull the next page of logs.  How would I get the next page of logs?

Thank you,
Craig

**Comment by gabrielsroka** [comment]
Hi Craig
Check out the readme. It has a link to pagination:
https://developer.okta.com/docs/api/getting_started/design_principles#pagination

Also, I have sample code that might help:
https://github.com/gabrielsroka/OktaAPI.psm1/blob/master/CallOktaAPI.ps1#L192-L237

See also:
https://github.com/mbegan/Okta-Scripts/blob/master/saveEventLogs.md


On Oct 21, 2018 11:28 AM, "daviscraigs" <notifications@github.com> wrote:

Hi Gabriel,
I'm new to using APIs and am working on a PowerShell script to automate the
download of Okta system logs. I have Get-OktaLogs working and am able to
capture the numbers of log entries based on the -limit value. My
understanding is I should be able to then pull the next page of logs. How
would I get the next page of logs?

Thank you,
Craig

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/gabrielsroka/OktaAPI.psm1/issues/3#issuecomment-431692184>,
or mute the thread
